DROP SCHEMA IF EXISTS SMART_CART;
CREATE SCHEMA SMART_CART;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
	CUST_ID VARCHAR(50) PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	GENDER VARCHAR(10)
);

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(
	ADDR_TYPE VARCHAR(10),
	STREET1 VARCHAR(50),
	STREET2 VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PIN VARCHAR(50),
	COUNTRY VARCHAR(50),
	CUTOMER_ID VARCHAR(50),
	
	FOREIGN KEY(CUTOMER_ID) REFERENCES CUSTOMER(CUST_ID)
);


DROP TABLE IF EXISTS ORD;
CREATE TABLE ORD(
	ORDER_ID VARCHAR(55),
	ORDER_DESC VARCHAR(255),
	BILL_AMOUNT DECIMAL,
);